os:
  - osx
language: objective-c
osx_image: xcode8.2
script: xcodebuild test -enableCodeCoverage YES -project PhotosPlus.xcodeproj -scheme PhotosPlus  -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.1'
